
pipeline {
    agent any
    options {
        ansiColor('xterm')
    } 
    parameters {
		//string(name: "git_codebase", defaultValue: "https://github.com/rstraining4/terraform-ci-pipelines.git", description: "git location of the updatedb app files")
        choice(
                choices: ["build","release-start","releasebuild","release-finish"],
                description: "Build from <env>elop branch, start a release or finish from release branch",
                name: "REQUESTED_ACTION")
}

	environment {
		image_version_ui=""
	}

//------------------------------------------
// Building DB Update jar
//------------------------------------------
    stages {
        stage('Terraform code checkout') { 
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/rstraining4/terraform-ci-pipelines.git']]])
            }
        }
        stage('BUILD JAR') { 
            steps {
                    checkout scm
                    sh 'git log -n1 --format="%h"'
                    sh "cd /var/lib/jenkins/workspace/prod/CI_Pipelines/terraform-ecs-ec2-ci/terraform-ecs-ec2"
                    sh "pwd"
                    sh "ls -lat"
                    sh "/usr/bin/mvn clean install"
                    sh "mv target/sasaws-0.0.1-SNAPSHOT.jar ."
            }
        }

//------------------------------------------
// Docker Login
//------------------------------------------
        stage("Docker Login,build,push") {
           // when { branch 'master' }
            steps {

                 sh '''
					commitid=$(git log -n1 --format="%h")
					echo $commitid
					cwd=$(pwd)
                        # Get docker login command
                        docker_login_cmd=\$(aws ecr get-login --region ap-south-1 --no-include-email)

                        # Login to docker
                         eval \$docker_login_cmd
                        # Docker build
                        docker build -t demo-ui:$commitid -f Dockerfile .
                        docker tag demo-ui:$commitid 398250248933.dkr.ecr.ap-south-1.amazonaws.com/ecs-ec2/demo-ui:$commitid
                        docker push 398250248933.dkr.ecr.ap-south-1.amazonaws.com/ecs-ec2/demo-ui:$commitid
                        docker image rm demo-ui:$commitid
                        docker image rm 398250248933.dkr.ecr.ap-south-1.amazonaws.com/ecs-ec2/demo-ui:$commitid
                    '''
            }
        }
//------------------------------------------------
// Update ECS task 
//------------------------------------------------
       	stage('Update ECS tasks & services') { 
            steps {
				script {
					image_version_ui = sh(script:'git log -n1 --format="%h"', returnStdout: true).trim()				
					build job: 'TERRAFORM-PROJECT-NAME', parameters: [[$class: 'StringParameterValue', name: 'terra_action', value: 'apply'], [$class: 'StringParameterValue', name: 'git_codebase', value: 'https://github.com/rstraining4/terraform-ci-pipelines.git'], [$class: 'StringParameterValue', name: 'main_dir_name', value: 'SAS_to_S3_Project/main'], [$class: 'StringParameterValue', name: 'tf_vars', value: "image_version_ui=${image_version_ui}"]]
				}
			}
        } 
    }
}